### ISSUE TITLE
Template for a Travis CI smoke-test build

### ISSUE THREAD

**Issue by jeffque** [TotalCross/totalcross#64]
## Template for a Travis CI smoke-test build
Travis CI is a widely used CI platform for open source projects that has tight integartion with GitHub. I would appreciate if there was a template build to check if the project is compiling

### Other CIs available
There is also CircleCI available, but it has a limitation for FOSS build time, the TotalCross dependencies take time to download and I have no idea of how to control the cache of it for FOSS projects. For example, it took 31s to download and compile a [project](https://jitpack.io/com/gitlab/geosales-open-source/totalcross-resultset-extractor/1.0.1-retrolambda/build.log) with basically TotalCross 4.4.2 and Retrolambda dependency and 5 Java files in JitPack.

So, yes, I have no interest in a CircleCI template for now

JitPack I use solely for distributing FOSS libraries, and it works building the source code when a tag is pushed AND some project requires that Maven dependency, so it is not suitable for this task.

GitLab-CI allows me to compile with any Docker Image, and it also let me configure cache for warming-up build stages. But it is solely to GitLab projects, not suitable for GitHub projects.

## Describe the bug
I would like to check, for every and each push, if the code is compiling correctly with TotalCross, in a way that any accidental code incompatibility is detected and thus solved quickly. Like, for the CoronaChartApp.

## Additional context
I would easily create a smoke test with [`tc-compiler-help`](https://gitlab.com/geosales-open-source/tc-compiler-help) adding the `.setDryRun(true)` option to the build, as I have done [here](https://gitlab.com/geosales-open-source/totalcross-resultset-extractor/-/blob/master/performance/src/main/java/br/com/softsite/rsextractor/PerformanceTest.java#L66) for the [TotalCross ResultSet Extractor](https://gitlab.com/geosales-open-source/totalcross-resultset-extractor) library.

As TotalCross ResultSet Extractor is a GitLab project, I used there the "native" GitLab-CI for [this task](https://gitlab.com/geosales-open-source/totalcross-resultset-extractor/-/blob/9170f8f8197073cb87776ab404ba6b5fed7baec4/.gitlab-ci.yml#L28-37):

```yml
tc-build:
  stage: tc-build
  dependencies:
    - build
  script:
    - ./mvnw $MAVEN_CLI_OPTS clean install -P retrolambda
    - ln -vs $PWD/.m2 performance/.m2
    - ln -vs $PWD/mvnw performance/mvnw
    - cd performance
    - ./mvnw $MAVEN_CLI_OPTS clean package -P retrolambda,dev exec:java -Dexec.mainClass=br.com.softsite.rsextractor.PerformanceTest -Dexec.args=-n
```

But I get lost in Travis CI way of declaring "os", "language", etc. I find it way easier to work with GitLab-CI as I can rely on any docker image, so I have no problem with it.
